### ISSUE TITLE
do query-params-store support angular 9?

### ISSUE THREAD

**Issue by FinalDes** [IliaIdakiev/query-param-store#21]
have warning when install on angular 9.1 are they can be ignore?
```
warning " > query-params-store@3.1.0" has incorrect peer dependency "@angular/common@^8.0.0".
warning " > query-params-store@3.1.0" has incorrect peer dependency "@angular/core@^8.0.0".
```

**Comment by IliaIdakiev** [comment]
Hello @FinalDes, there is no problem to use it with angular 9. This are just warnings as you see that will be resolved soon. I'm doing some refactoring on the library now so it can be better structured and more readable for new contributors. I will also do some optimisations so I can limit the calculations being done. It will be ready in the next few days. Cheers!
